---
- name: Deploy / build server
  hosts: deploy
  roles:
    - name: preconfig
      tags: preconfig
    - role: build
      tags: build
    - role: deploy
      tags: deploy
      
- name: Manager
  hosts: managers
  roles:
    - name: preconfig
      tags: preconfig

- name: Worker
  hosts: workers
  roles:
    - name: preconfig
      tags: preconfig