---
- name: Deploy / build server
  hosts: deploy
  roles:
    - name: preconfig
      tags: preconfig
    - role: build
      tags: build
    - role: deploy
      tags: deploy
    - role: swarm_init
      tags: swarm_init
      
- name: Manager
  hosts: managers
  roles:
    - name: preconfig
      tags: preconfig
    - role: swarm_join
      type: manager
      tags: swarm_join

- name: Worker
  hosts: workers
  roles:
    - name: preconfig
      tags: preconfig
    - role: swarm_join
      type: worker
      tags: swarm_join