---
- name: "[{{ name }}] Создаем секрет"
  include: "../secret.yml"

- name: "[{{ name }}] Выкладываем сервис"
  community.docker.docker_swarm_service:
    name: "{{ name }}"
    image: "localhost:5000/api:latest"
    state: present
    networks:
      - name: "{{ network_name }}"
    publish:
      - mode: ingress
        protocol: tcp
        published_port: 3002
        target_port: 3000
    secrets:
      - secret_name: "{{ name }}.env"
        filename: "/opt/app/.env"

- name: Print the gateway for each host when defined
  ansible.builtin.debug:
    msg: "{{ name }}"
  when: name is defined